<?php

return [
    // Aa
    'Á' => '&Aacute;',
    'á' => '&aacute;',
    'Â' => '&Acirc;',
    'â' => '&acirc;',
    'À' => '&Agrave;',
    'à' => '&agrave;',
    'Å' => '&Aring;',
    'å' => '&aring;',
    'Ã' => '&Atilde;',
    'ã' => '&atilde;',
    'Ä' => '&Auml;',
    'ä' => '&auml;',
    'Æ' => '&AElig;	',
    'æ' => '&aelig;',
    // Ee
    'É' => '&Eacute;',
    'é' => '&eacute;',
    'Ê' => '&Ecirc;',
    'ê' => '&ecirc;',
    'È' => '&Egrave;',
    'è' => '&egrave;',
    'Ë' => '&Euml;',
    'ë' => '&euml;',
    'Ð' => '&ETH;',
    'ð' => '&eth;',
    // Ii
    'Í' => '&Iacute;',
    'í' => '&iacute;',
    'Î' => '&Icirc;',
    'î' => '&icirc;',
    'Ì' => '&Igrave;',
    'ì' => '&igrave;',
    'Ï' => '&Iuml;',
    'ï' => '&iuml;',
    // Oo
    'Ó' => '&Oacute;',
    'ó' => '&oacute;',
    'Ô' => '&Oacirc;',
    'ô' => '&oacirc;',
    'Ò' => '&Ograve;',
    'ò' => '&ograve;',
    'Ø' => '&Oslash;',
    'ø' => '&oslash;',
    'Õ' => '&Otilde;',
    'õ' => '&otilde;',
    'Ö' => '&Ouml;',
    'ö' => '&ouml;',
    // Uu
    'Ú' => '&Uacute;',
    'ú' => '&uacute;',
    'Û' => '&Uacirc;',
    'û' => '&uacirc;',
    'Ù' => '&Uagrave;',
    'ù' => '&uagrave;',
    'Ü' => '&Uauml;',
    'ü' => '&uauml;',
    // Çç
    'Ç' => '&Ccedil;',
    'ç' => '&ccedil;',
    // Nn
    'Ñ' => '&Ntilde;' ,
    'ñ' => '&ntilde;' ,
    // Yy
    'Ý' => '&Yacute;',
    'ý' => '&yacute;',
    // Simbols
    '"' => '&quot;',
    '<' => '&lt;',
    '>' => '&gt;',
    '&' => '&amp;',
    '®' => '&reg;',
    '©' => '&copy;',
    'Þ' => '&THORN;',
    'þ' => '&thorn;',
    'ß' => '&szlig;',
];